[language-server]
biome = { command = "biome", args = ["lsp-proxy"] }

[[language]]
name = "json"
auto-format = false

[[language]]
name = "toml"

[[language]]
name = "bash"

[[language]]
name = "php"

[language-server.intelephense.config]

[language-server.typescript-language-server.config]
plugins = [{  name = "@vue/typescript-plugin", location = "/Users/jacksonfrankland/Library/pnpm/vue-language-server", languages = ["vue"] }]
tsserver = { path = "/Users/jacksonfrankland/Library/pnpm/tsserver" }

[language-server.vuels]
command = "vue-language-server"
args = ["--stdio"]

[[language]]
name = "vue"
auto-format = true
language-servers = ["typescript-language-server", "vuels"]
formatter = { command = 'prettier', args = ["--tab-width", "4", "--single-quote", "--no-semi", "--parser", "vue"] } 
# formatter = { command = "pnpm", args = ["exec","biome","check", "--stdin-file-path=%{buffer_name}", "--write"] }
[[language]]
name = "html"

[[languages]]
name = "go"
auto-format = true
formatter = { command = "goimports" }

[[languages]]
name = "bash"
file-types = ["sh", "bash", ".functions"]

[[language]]
name = "svelte"
text-width = 120
scope = "source.svelte"
injection-regex = "svelte"
file-types = ["svelte"]
language-servers = [
  "svelteserver",
  # "emmet-lsp",
  # "efm-lsp",
  # "eslint",
  "tailwindcss-ls",
]
